import './globals.css'
import Sidebar from '@/components/sidebar'

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-sky-100 bg-no-repeat'>
        <div className='flex flex-row w-[1000px] mx-auto mt-[90px]'> 
        <Sidebar/>
        <main className='flex flex-grow'>{children}</main>
        </div>
        </body>
    </html>
  )
}
